# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoadorLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='doador.Doador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
