# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
