# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_auto_20161013_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=500)),
                ('valor', models.IntegerField()),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ong.Ong')),
            ],
        ),
    ]
