# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_auto_20161013_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_ROOT'),
        ),
    ]
