# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0003_dispesas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dispesas',
            new_name='Despesas',
        ),
    ]
