# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0004_auto_20161025_2245'),
        ('ong', '0003_auto_20161027_1354'),
    ]

    operations = [
    ]
