# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0005_merge_20161108_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='img/ong'),
        ),
    ]
